application: nodal-magnet-740
version: 1
runtime: go
api_version: go1

handlers:
#- url: /stylesheets
#  static_dir: stylesheets

#- url: /(.*\.(gif|png|jpg))$
#  static_files: static/\1
#  upload: static/.*\.(gif|png|jpg)$
- url: /js
  static_dir: static/js/
- url: /img
  static_dir: static/img/
- url: /svg-sprite
  static_dir: static/svg-sprite/
- url: /css-sprite
  static_dir: static/css-sprite/
- url: /tmpl
  static_dir: static/tmpl/
# - url: /css
#   static_dir: bower_components/angular-material/
- url: /css
  static_dir: static/css/
- url: /auth/google
  script: _go_app
- url: /api/.*
  script: _go_app

- url: /.*
  static_files: static/index.html
  upload: static/index.html
